// Copyright 2018-2024 Sam Windell
// SPDX-License-Identifier: GPL-3.0-or-later

#define SIDEBAR_IMAGE_RESOURCE_ID 300
#define CLAP_PLUGIN_RESOURCE_ID   301
#define VST3_PLUGIN_RESOURCE_ID   302
#define UNINSTALLER_RESOURCE_ID   303

#define RAW_DATA_TYPE 600
