// Copyright 2018-2026 Sam Windell
// SPDX-License-Identifier: GPL-3.0-or-later

#include "foundation/foundation.hpp"
#include "os/misc.hpp"
#include "os/threading.hpp"
#include "utils/cli_arg_parse.hpp"

#include "common_infrastructure/global.hpp"

#include "distortion_measurement.hpp"

static void AppendCurve(DynamicArray<char>& source, Span<f32 const> curve, String indent) {
    fmt::Append(source, "{}{{", indent);
    for (auto const bucket : Range(curve.size)) {
        if (bucket != 0) fmt::Append(source, ",");
        if (bucket % 8 == 0) fmt::Append(source, "\n{}   ", indent);
        fmt::Append(source, " {.7}f", curve[bucket]);
    }
    fmt::Append(source, "\n{}}},\n", indent);
}

static ErrorCodeOr<int> Main(ArgsCstr) {
    auto const table = ComputeDistortionNormTable();

    ArenaAllocator arena {PageAllocator::Instance()};
    DynamicArray<char> source {arena};

    // The licence tag is assembled at runtime so the REUSE checker doesn't read this format string as this
    // file's own header.
    fmt::Append(source,
                "// Copyright 2018-2026 Sam Windell\n"
                "// {}: GPL-3.0-or-later\n\n"
                "// Generated by \"zig build script:gen-distortion-table\". Do not edit by hand.\n"
                "#pragma once\n\n"
                "constexpr DistortionNormTable k_distortion_norm_table {{\n"
                "    .stage_gain = {{{{\n",
                "SPDX-License-Identifier");
    for (auto const type_index : Range(k_num_distortion_types)) {
        fmt::Append(source, "        // {}\n", k_distortion_type_strings[type_index]);
        AppendCurve(source, table.stage_gain[type_index], "        ");
    }
    fmt::Append(source, "    }}}},\n    .punish_gain = {{{{\n");
    for (auto const type_index : Range(k_num_distortion_types)) {
        fmt::Append(source, "        // {}\n        {{{{\n", k_distortion_type_strings[type_index]);
        for (auto const punish_bucket : Range((usize)DistortionNormTable::k_num_punish_buckets)) {
            fmt::Append(source,
                        "            // punish {}/{}\n",
                        punish_bucket,
                        DistortionNormTable::k_num_punish_buckets - 1);
            AppendCurve(source, table.punish_gain[type_index][punish_bucket], "            ");
        }
        fmt::Append(source, "        }}}},\n");
    }
    fmt::Append(source, "    }}}},\n}};\n");

    TRY(StdPrint(StdStream::Out, source.Items()));

    return 0;
}

int main(int argc, char** argv) {
    auto _ = EnterLogicalMainThread();
    GlobalInit({
        .init_error_reporting = false,
        .set_main_thread = true,
        .panic_response = PanicResponse::Abort,
    });
    DEFER { GlobalDeinit({.shutdown_error_reporting = false}); };
    auto result = Main({argc, argv});
    if (result.HasError()) {
        StdPrintF(StdStream::Err, "Error: {}", result.Error());
        return 1;
    }
    return result.Value();
}
