# generated by zon2nix (https://github.com/jcollie/zon2nix)
{
  lib,
  linkFarm,
  fetchzip,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig_0_15,
  zstd,
  name ? "zig-packages",
}:
let
  unpackZigArtifact =
    {
      name,
      artifact,
    }:
    runCommandLocal name
      {
        nativeBuildInputs = [ zig_0_15 ];
      }
      ''
        hash="$(cd "$TMPDIR" && zig fetch --global-cache-dir "$TMPDIR" ${artifact})"
        mv "$TMPDIR/p/$hash" "$out"
        chmod 755 "$out"
      '';

  fetchZig =
    {
      name,
      url,
      hash,
      unpack,
    }:
    let
      artifact =
        if unpack then
          fetchzip {
            inherit url hash;
            nativeBuildInputs = [ zstd ];
          }
        else
          fetchurl { inherit url hash; };
    in
    unpackZigArtifact { inherit name artifact; };

  fetchGitZig =
    {
      name,
      url,
      hash,
    }:
    let
      parts = lib.splitString "#" url;
      url_base = builtins.elemAt parts 0;
      url_without_query = builtins.elemAt (lib.splitString "?" url_base) 0;
      rev_base = builtins.elemAt parts 1;
      rev =
        if builtins.match "^[a-fA-F0-9]{40}$" rev_base != null then rev_base else "refs/heads/${rev_base}";
    in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
      fetchSubmodules = false;
    };

  fetchZigArtifact =
    {
      name,
      url,
      hash,
      unpack,
    }:
    let
      parts = lib.splitString "://" url;
      proto = builtins.elemAt parts 0;
      path = builtins.elemAt parts 1;
      fetcher = {
        "git+http" = fetchGitZig {
          inherit name hash;
          url = "http://${path}";
        };
        "git+https" = fetchGitZig {
          inherit name hash;
          url = "https://${path}";
        };
        http = fetchZig {
          inherit name hash unpack;
          url = "http://${path}";
        };
        https = fetchZig {
          inherit name hash unpack;
          url = "https://${path}";
        };
      };
    in
    fetcher.${proto};
in
linkFarm name [
  {
    name = "N-V-__8AABXaAwCPe89grjjAXjcvmKwtSHo-0bx570E4IGYf";
    path = fetchZigArtifact {
      name = "audio_unit_sdk";
      url = "https://github.com/floe-audio/AudioUnitSDK/archive/refs/tags/v1.1.0.tar.gz";
      hash = "sha256-LtnK5MBq5N94XigblYX0njOoUY64+YOaeCDlUYDPgl4=";
      unpack = false;
    };
  }
  {
    name = "N-V-__8AAGWdHwpFLhcKRmman91iiYjX9G4gIlvwSFEnzz6N";
    path = fetchZigArtifact {
      name = "bgfx";
      url = "git+https://github.com/bkaradzic/bgfx#fbff26d5e5943ce20e4e67b2247100bbfb216ad1";
      hash = "sha256-2HwXibbeh/pvYyEsmQyNj/hTSuAfppcPmZsQkMsp3zo=";
      unpack = true;
    };
  }
  {
    name = "N-V-__8AAFpnOQB6_cqjml8VTQsqI9pWa7OWoIL3geoldRHy";
    path = fetchZigArtifact {
      name = "bimg";
      url = "git+https://github.com/bkaradzic/bimg#4f1916fca2a0ae1ed9d6e0424323cd45fe2d6ed5";
      hash = "sha256-H0zSVdxGU8d4pxJXI8AJj/Ly2Js/L5MSGYzfspGfArA=";
      unpack = true;
    };
  }
  {
    name = "N-V-__8AAEf5TQCNdZyN4RGDyeTw-jnJskEC9uHwZi0qXX9n";
    path = fetchZigArtifact {
      name = "bx";
      url = "git+https://github.com/bkaradzic/bx#a5ce3bed947ab1c9e386f1c98f0ed66cf4eb410f";
      hash = "sha256-DtF+4OLmBxMxy9sj9YWZNOArmQBLYhbfc35nNAS1I5o=";
      unpack = true;
    };
  }
  {
    name = "N-V-__8AAJ0IOwDGU09eyNgdU99_TixuQnS6E7dLq1bSlvNA";
    path = fetchZigArtifact {
      name = "clap";
      url = "https://github.com/free-audio/clap/archive/refs/tags/1.2.3.tar.gz";
      hash = "sha256-8s1Jo+RW/ROkwM7qsPlMuv0VhjpjU8B1BYPpCLPM9AM=";
      unpack = false;
    };
  }
  {
    name = "N-V-__8AAFDvhAD7wsMQHzT9s_hiRLUTXJp4mBwyx_O7gZxZ";
    path = fetchZigArtifact {
      name = "clap_validator_linux";
      url = "https://github.com/floe-audio/clap-validator/releases/download/v0.3.2/clap-validator-0.3.2-ubuntu-18.04.zip";
      hash = "sha256-854YUOddH/gfngh9fJM2Ly21ShydsgNMZnf6w7gOEX8=";
      unpack = false;
    };
  }
  {
    name = "N-V-__8AALwZfgBlaKnVwge3d221LJA9s_vQixy9c6OBvGhQ";
    path = fetchZigArtifact {
      name = "clap_validator_macos";
      url = "https://github.com/free-audio/clap-validator/releases/download/0.3.2/clap-validator-0.3.2-macos-universal.tar.gz";
      hash = "sha256-N1Dzcprf2EifKykBn38u1lunG/nVBJc19qLKD8yxj/0=";
      unpack = false;
    };
  }
  {
    name = "N-V-__8AAACYMwAKpkDTKEWrhJhUyBs1LxycLWN8iFpe5p6r";
    path = fetchZigArtifact {
      name = "clap_validator_windows";
      url = "https://github.com/free-audio/clap-validator/releases/download/0.3.2/clap-validator-0.3.2-windows.zip";
      hash = "sha256-aM2+UcBUiVQrVCCocLcVm0yzUrXOXEhvm9iptJt1vdo=";
      unpack = false;
    };
  }
  {
    name = "N-V-__8AADsCEQAQen0Jma51EHeja0rrbgees_m-UV4GbWGQ";
    path = fetchZigArtifact {
      name = "clap_wrapper";
      url = "git+https://github.com/SamWindell/clap-wrapper#b54e52394410d33ac0d4a8e420b21d8e8c0c3e37";
      hash = "sha256-lSM8Yy4awvXpjBHI1yiYLVMSYgMU4OZIZB1LHFcaPE0=";
      unpack = true;
    };
  }
  {
    name = "N-V-__8AAJpbLQAEwHIs7OLypQPQ7n5ICizvwIEb98KtT_9_";
    path = fetchZigArtifact {
      name = "dr_libs";
      url = "git+https://github.com/mackron/dr_libs#da35f9d6c7374a95353fd1df1d394d44ab66cf01";
      hash = "sha256-ydFhQ8LTYDBnRTuETtfWwIHZpRciWfqGsZC6SuViEn0=";
      unpack = true;
    };
  }
  {
    name = "N-V-__8AAGvoAQDmyU1FAg-fls7y6rWfjIUpUR25wnGzrQTD";
    path = fetchZigArtifact {
      name = "ebur128";
      url = "https://github.com/jiixyj/libebur128/archive/refs/tags/v1.2.6.tar.gz";
      hash = "sha256-uqf8KTo9RlHiRNgCKtA6t5fKPCrYRCxDGZr+gFn6phM=";
      unpack = false;
    };
  }
  {
    name = "N-V-__8AAHSrwgDkuwylGkEyZxj-_xKsppp8z8563UYjXs2B";
    path = fetchZigArtifact {
      name = "flac";
      url = "https://github.com/xiph/flac/releases/download/1.5.0/flac-1.5.0.tar.xz";
      hash = "sha256-8sHHZZKoL//4QTujxKEpm2x6sGxzTe4D/YhjBIXCuSA=";
      unpack = false;
    };
  }
  {
    name = "N-V-__8AAHEKFgBFuPa2_DBoERCMfyw108H3h7ubU7jLpXtj";
    path = fetchZigArtifact {
      name = "floe_logos";
      url = "git+https://github.com/floe-audio/Floe-Logos#8dcbe7fdfab93a7958947ad6d0ff9427565c65ab";
      hash = "sha256-Ibmtc8TTH8qp8GHfp7dJLWqO13EBRTsN4Bfil4rVuNg=";
      unpack = true;
    };
  }
  {
    name = "N-V-__8AANOnVADPVDjIiG7D_MKWmVQypIKAQFJ04Uc97KTA";
    path = fetchZigArtifact {
      name = "icon_font_cpp_headers";
      url = "git+https://github.com/juliettef/IconFontCppHeaders#f30b1e73b2d71eb331d77619c3f1de34199afc38";
      hash = "sha256-fmiZwzFVEaP4aXkJKB3LCKNRxM7/6+SXm+S/bU9et+E=";
      unpack = true;
    };
  }
  {
    name = "N-V-__8AAA2SGQDIowqfBdNuGGJ03b-aevlPIR3TaFV3knJ9";
    path = fetchZigArtifact {
      name = "lua";
      url = "https://github.com/lua/lua/archive/refs/tags/v5.4.7.tar.gz";
      hash = "sha256-XDkRGz/EwcnlZnEAiVWhcw9UoVuV4fG9B1K4aLkp2OM=";
      unpack = false;
    };
  }
  {
    name = "N-V-__8AAB9_nUSdLMKeije7VseY73LAq089gUM1JhO-EAWC";
    path = fetchZigArtifact {
      name = "macos_sdk";
      url = "https://github.com/joseluisq/macosx-sdks/releases/download/13.0/MacOSX13.0.sdk.tar.xz";
      hash = "sha256-bpvYaDhmr7MQ9Th1d0TGBqkk9bqbqnFVDOM36yaV0aI=";
      unpack = false;
    };
  }
  {
    name = "N-V-__8AAHNWwAASlNuYbrP1-3UqXdwbYvZ_6nIJhpAcRMfi";
    path = fetchZigArtifact {
      name = "miniaudio";
      url = "https://github.com/mackron/miniaudio/archive/refs/tags/0.11.25.tar.gz";
      hash = "sha256-uQDtz/6XmBbiVgoFgLmxIW1nS08X+63sqPd3p/irAnQ=";
      unpack = false;
    };
  }
  {
    name = "N-V-__8AAJmKFgANnVgLMCG4IKGFiSk_OceSUlZrQfI_Lo-r";
    path = fetchZigArtifact {
      name = "miniz";
      url = "https://github.com/richgel999/miniz/archive/refs/tags/3.1.2.tar.gz";
      hash = "sha256-mEaPiSSTS3IydmgPhSOLbHi/H4tJtEWcybchSiDi6fs=";
      unpack = false;
    };
  }
  {
    name = "N-V-__8AAN5xAwApRz_QkfXmd_6RJEz1Jh4YX3EwvaQ_Zolx";
    path = fetchZigArtifact {
      name = "pffft";
      url = "https://bitbucket.org/jpommier/pffft/get/fbc405860280.zip";
      hash = "sha256-AylL4pp3KsUV19Xwe/R1sQ/mRN8TL/Vt7koYM452dTM=";
      unpack = false;
    };
  }
  {
    name = "N-V-__8AAHiZqACvZuwhiWbvPBeJQd-K_5xpafp_Pi_6228J";
    path = fetchZigArtifact {
      name = "pluginval_linux";
      url = "https://github.com/Tracktion/pluginval/releases/download/v1.0.3/pluginval_Linux.zip";
      hash = "sha256-aa3IfWu7L3IkoDjY+MXnN+pckG6hU3UrilRrYSXgVk8=";
      unpack = false;
    };
  }
  {
    name = "N-V-__8AAF8tGQHuEhO2q5y6oj6foKiCHCXCQWbfpY6ehS5e";
    path = fetchZigArtifact {
      name = "pluginval_macos";
      url = "https://github.com/Tracktion/pluginval/releases/download/v1.0.3/pluginval_macOS.zip";
      hash = "sha256-a7TQrMlk53WvFV7JhMFWbcmJ2tKnCPZMdzcG17rsQ68=";
      unpack = false;
    };
  }
  {
    name = "N-V-__8AAABcNACEKUY1SsEfHGFybDSKUo4JGhYN5bgZ146c";
    path = fetchZigArtifact {
      name = "pluginval_windows";
      url = "https://github.com/Tracktion/pluginval/releases/download/v1.0.3/pluginval_Windows.zip";
      hash = "sha256-TYO94hrrr01S7Aym2fDHEZrUGBKI64LaED+t4xqFI60=";
      unpack = false;
    };
  }
  {
    name = "N-V-__8AANbpCgD12WyFfiC-ftVufWE_syD8oWqSURyueGec";
    path = fetchZigArtifact {
      name = "portmidi";
      url = "git+https://github.com/PortMidi/portmidi#8efac0cfe6c245aeb2ce5122aa2b82fb79e91463";
      hash = "sha256-xLZEG1j+KwAVJ4EfMhedUXjKikuQ49t01kmEs/QuvMI=";
      unpack = true;
    };
  }
  {
    name = "N-V-__8AAN4dEAARU97STYhcsp8KtZa1D3I_Laz6Nj0IWEfT";
    path = fetchZigArtifact {
      name = "pugl";
      url = "git+https://github.com/SamWindell/pugl#8a6b26e0f06ec44971faef4f2319a4644067fab1";
      hash = "sha256-fuv1PT53IZzcSstOkEeW0Lr+4HjLHDUuS2wDRdEvcEI=";
      unpack = true;
    };
  }
  {
    name = "N-V-__8AAEcaTgC0PvsOioipLsVPn4WYe6IJlznmnWu0m5sh";
    path = fetchZigArtifact {
      name = "stb";
      url = "git+https://github.com/nothings/stb#64e783d73879abe2e7589bc634bf6cb6f5e2baae";
      hash = "sha256-kx/vZBm6YLKNmlHrR8gOvIrHEIWn+WQcLyMqocC99Bk=";
      unpack = true;
    };
  }
  {
    name = "N-V-__8AANdYcwFozAnhesSHS-Tdgtfe30bGHvDiiOPNdo57";
    path = fetchZigArtifact {
      name = "tracy";
      url = "https://github.com/wolfpld/tracy/archive/refs/tags/v0.14.0.tar.gz";
      hash = "sha256-qTLPKpCtv2P4e0SfpDdKUvGKNsSjhY1NadPnXWL6X2o=";
      unpack = false;
    };
  }
  {
    name = "N-V-__8AAMV2BgB9aKHnchADe5onASuvEqAeRRO7Ai1oTuzW";
    path = fetchZigArtifact {
      name = "valgrind_h";
      url = "https://github.com/allyourcodebase/valgrind.h/archive/refs/tags/3.23.0.tar.gz";
      hash = "sha256-MLyxrVhfqhibCEuDOL3hSUJbXJMEi0jLxDO46Xt6IL4=";
      unpack = false;
    };
  }
  {
    name = "N-V-__8AAO0bUAGCcGr95wyEMO9MxddzMb9rGpxf6yLBEiIE";
    path = fetchZigArtifact {
      name = "vst3_sdk";
      url = "https://github.com/floe-audio/vst3sdk/archive/refs/tags/v3.7.9.tar.gz";
      hash = "sha256-tztZ6nFR/k8kLyfq+ovWZhG/WRv/VSMdQWPKTith0UU=";
      unpack = false;
    };
  }
  {
    name = "N-V-__8AAExyUgDx-txe2Gg6EHaVFT1HUCXO-WGf0FBABDq-";
    path = fetchZigArtifact {
      name = "xxhash";
      url = "https://github.com/Cyan4973/xxHash/archive/refs/tags/v0.8.2.tar.gz";
      hash = "sha256-uu4Mav1PAxZd56TmeYjRbw8rJXtR0OPLkZCTAqJqecQ=";
      unpack = false;
    };
  }
]
