# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2024 Sam Windell

version = 1
SPDX-PackageName = "Floe"
SPDX-PackageSupplier = "Sam Windell"
SPDX-PackageDownloadLocation = "https://github.com/floe-synth/floe"

[[annotations]]
path = "test_files/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Sam Windell"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "docs/src/images/*"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024-2025 Sam Windell"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["**.lock", "build_resources/**.lock", "version.txt"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Sam Windell"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["build_resources/reverb_irs/**.flac"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Sam Windell"
SPDX-License-Identifier = "CC0-1.0"
