# Copyright 2024 Sam Windell
# SPDX-License-Identifier: GPL-3.0-or-later

# NOTE: mdbook has font-awesome 4.7 icons built in

[book]
authors = ["Sam Windell"]
language = "en"
multilingual = false
src = "src"
title = "Floe"
description = "Floe is a free, open-source sample library engine. Available as an audio plugin for Windows and macOS."

[output.html]
default-theme = "rust"
preferred-dark-theme = "coal"
smart-punctuation = true
git-repository-url = "https://github.com/Floe-Project/Floe"
cname = "floe.audio"
additional-css = ["theme/floe-theme.css"]
