# Copyright 2025 Sam Windell
# SPDX-License-Identifier: GPL-3.0-or-later

name: Deploy Website

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types: [published] # our website needs to update its download links

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - uses: nicknovitski/nix-develop@v1.2.1
      - uses: Hanaasagi/zig-action-cache@master

      - run: just build native

      - run: just install-docs-preprocessor

      - name: Deploy GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd docs
          wget https://raw.githubusercontent.com/floe-audio/Floe-Logos/main/rasterized/favicon.png -P theme
          wget https://raw.githubusercontent.com/floe-audio/Floe-Logos/main/rasterized/favicon.svg -P theme
          mdbook build
          git worktree add gh-pages
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          cd gh-pages
          # Delete the ref to avoid keeping history.
          git update-ref -d refs/heads/gh-pages
          rm -rf *
          mv ../book/* .
          git add .
          git commit -m "Deploy $GITHUB_SHA to gh-pages"
          git push --force --set-upstream origin gh-pages
