# Copyright 2024-2025 Sam Windell
# SPDX-License-Identifier: GPL-3.0-or-later

name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

env:
  SENTRY_DSN: ${{ secrets.SENTRY_DSN_DEVELOPMENT }}

jobs:
  mac-compile-and-test:
    runs-on: macos-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - uses: nicknovitski/nix-develop@v1.1.0
      - uses: Hanaasagi/zig-action-cache@master
        with:
          cache-directories: |
            .floe-cache

      - run: just build mac_ub
      - run: just install-docs-preprocessor
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: just test-ci

      - name: Upload errors
        if: '!cancelled()'
        run: just upload-errors

      - name: Upload logs
        if: '!cancelled()'
        uses: actions/upload-artifact@v4
        with:
          name: logs-macos
          if-no-files-found: ignore
          path: ~/Library/Logs/Floe/*

  linux-compile-and-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - uses: nicknovitski/nix-develop@v1.1.0
      - uses: Hanaasagi/zig-action-cache@master
        with:
          cache-directories: |
            .floe-cache

      - if: '!cancelled()'
        run: just build native

      - if: '!cancelled()'
        run: just build windows

      - if: '!cancelled()'
        run: just build mac_ub

      - if: '!cancelled()'
        run: just install-docs-preprocessor

      - if: '!cancelled()'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: just test-ci

      - if: '!cancelled()'
        name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: .floe-cache/coverage-out/tests
          verbose: true
          fail_ci_if_error: true

      # IMPORTANT(upload-artifact): 
      #  1. If multiple paths are provided as input, the least common ancestor of all the search paths will be used as the 
      #     root directory of the artifact. 
      #  2. All file permissions are removed when uploading.

      - name: Upload Windows binaries
        if: '!cancelled()'
        uses: actions/upload-artifact@v4
        with:
          name: binaries-windows
          if-no-files-found: error
          retention-days: 2
          path: |
            zig-out/x86_64-windows/Floe.vst3
            zig-out/x86_64-windows/Floe.clap
            zig-out/x86_64-windows/tests.exe
            zig-out/x86_64-windows/VST3-Validator.exe
            zig-out/x86_64-windows/Floe-Installer*.exe

      - name: Upload errors
        if: '!cancelled()'
        run: just upload-errors

      - name: Upload logs
        if: '!cancelled()'
        uses: actions/upload-artifact@v4
        with:
          name: logs-linux
          if-no-files-found: ignore
          path: ~/.local/state/Floe/Logs/*

  windows-test:
    runs-on: windows-latest
    needs: linux-compile-and-test
    if: '!cancelled()'
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            build_resources
            test_files
            justfile

      - uses: taiki-e/install-action@just

      - uses: actions/download-artifact@v4
        with:
          name: binaries-windows
          path: zig-out/x86_64-windows

      - run: just test-ci-windows

      - name: Run installer in auto mode
        if: '!cancelled()'
        run: just test-windows-installer

      - name: Install sentry-cli
        if: '!cancelled()'
        run: |
          choco install sentry-cli -y --no-progress
          sentry-cli --version

      - name: Upload errors
        if: '!cancelled()'
        run: just upload-errors

      - name: Upload logs
        if: '!cancelled()'
        uses: actions/upload-artifact@v4
        with:
          name: logs-windows
          if-no-files-found: ignore
          path: ~/AppData/Local/Floe/Logs/*
  
  notify:
    # We run this for main/develop, and also for PRs that are not from forks; in other words, PRs originating from Floe devs.
    if: ${{ ((github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop') || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)) && !cancelled() }}
    runs-on: ubuntu-latest
    needs: [linux-compile-and-test, windows-test, mac-compile-and-test]
    steps:
      - run: |
          report="Floe CI"
          report_job() {
            job=$1
            result=$2
            if [ "$result" == "success" ]; then
              report="$report | $job: ✅"
            else
              report="$report | $job: ❌"
            fi
          }
          report_job "Windows" ${{ needs.windows-test.result }}
          report_job "Mac" ${{ needs.mac-compile-and-test.result }}
          report_job "Linux" ${{ needs.linux-compile-and-test.result }}

          curl -d "$report" "ntfy.sh/${{ secrets.NTFY_CI_URL }}"
