
name: Windows Just
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/scripts/just-test

      - shell: bash
        run: mv .github/scripts/just-test justfile

      - uses: taiki-e/install-action@just

      - name: "1"
        if: '!cancelled()'
        shell: powershell
        run: |
          just test-env

      - name: "2"
        if: '!cancelled()'
        shell: bash
        run: |
          just test-env

      - name: "3"
        if: '!cancelled()'
        run: |
          just test-env


